server:
  port: 8282

spring:
  application:
    name: APP
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graphql_app
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
